# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget3(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 80, 381, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.Client3_Keyloggs = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.Client3_Keyloggs.setReadOnly(True)
        self.Client3_Keyloggs.setObjectName("Client3_Keyloggs")
        self.verticalLayout_2.addWidget(self.Client3_Keyloggs)
        self.layoutWidget_2 = QtWidgets.QWidget(Widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 80, 258, 430))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Client3_ComputerInformation = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.Client3_ComputerInformation.setReadOnly(True)
        self.Client3_ComputerInformation.setObjectName("Client3_ComputerInformation")
        self.verticalLayout.addWidget(self.Client3_ComputerInformation)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Client3_GeoLocatoin = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.Client3_GeoLocatoin.setReadOnly(True)
        self.Client3_GeoLocatoin.setObjectName("Client3_GeoLocatoin")
        self.verticalLayout.addWidget(self.Client3_GeoLocatoin)
        self.layoutWidget_3 = QtWidgets.QWidget(Widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(430, 390, 301, 111))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ComputerSelection = QtWidgets.QComboBox(self.layoutWidget_3)
        self.ComputerSelection.setObjectName("ComputerSelection")
        self.ComputerSelection.addItem("")
        self.ComputerSelection.addItem("")
        self.ComputerSelection.addItem("")
        self.ComputerSelection.addItem("")
        self.ComputerSelection.addItem("")
        self.gridLayout.addWidget(self.ComputerSelection, 0, 0, 1, 1)
        self.RefreshButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.RefreshButton.setObjectName("RefreshButton")
        self.gridLayout.addWidget(self.RefreshButton, 1, 1, 1, 1)
        self.SendLogViaEmail = QtWidgets.QPushButton(self.layoutWidget_3)
        self.SendLogViaEmail.setObjectName("SendLogViaEmail")
        self.gridLayout.addWidget(self.SendLogViaEmail, 0, 1, 1, 1)
        self.SetComputerInfo = QtWidgets.QPushButton(self.layoutWidget_3)
        self.SetComputerInfo.setObjectName("SetComputerInfo")
        self.gridLayout.addWidget(self.SetComputerInfo, 1, 0, 1, 1)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_3.setText(_translate("Widget", "Key Logs"))
        self.label.setText(_translate("Widget", "Computer Information"))
        self.label_2.setText(_translate("Widget", "Geo-Location Information"))
        self.ComputerSelection.setItemText(0, _translate("Widget", "Computer 1"))
        self.ComputerSelection.setItemText(1, _translate("Widget", "Computer 2"))
        self.ComputerSelection.setItemText(2, _translate("Widget", "Computer 3"))
        self.ComputerSelection.setItemText(3, _translate("Widget", "Computer 4"))
        self.ComputerSelection.setItemText(4, _translate("Widget", "Computer 5"))
        self.RefreshButton.setText(_translate("Widget", "Refresh"))
        self.SendLogViaEmail.setText(_translate("Widget", "Send Via Log Via Email"))
        self.SetComputerInfo.setText(_translate("Widget", "Set Computer Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget3()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
